"""Write the agent's LangGraph as Mermaid to docs/graph.md.

Builds the graph exactly as a question would, but never runs it: an empty
in-memory SQLite database and tracing off, so no model calls and nothing sent
anywhere. Run with `make graph` after changing nodes or edges.
"""

from pathlib import Path

from sqlalchemy import create_engine

from sqlagent.agent_graph import build_agent_graph
from sqlagent.config import Settings
from sqlagent.pipeline import SqlAgent

OUT = Path(__file__).resolve().parents[1] / "docs" / "graph.md"

HEADER = """# The agent graph

Generated by `make graph` (`scripts/draw_graph.py`) from
`build_agent_graph()` in `src/sqlagent/agent_graph.py` via LangGraph's
`get_graph().draw_mermaid()`. Do not edit by hand; regenerate.

- **Solid arrow**: always taken.
- **Dotted arrow**: conditional, chosen by a routing function
  (`route_after_*` in `agent_graph.py`).
- Loops back to `build_context` / `select_tables` / `widen_schema` are the
  repair loops; `give_up` is the exit when the budget runs out or a question
  needs clarifying.

In Langfuse each node appears under a verb-first name: `screen` →
`screen-question`, `select_tables` →
`select-tables`, `build_context` → `build-schema-context`, `generate_sql` →
`generate-sql`, `criticise` → `review-sql`, `validate_and_execute` →
`execute-sql`, `check_intent` → `check-intent`, `widen_schema` →
`widen-schema`, `write_answer` → `write-answer`, `give_up` → `give-up`.

"""


def main() -> None:
    config = Settings(_env_file=None, database_url="sqlite://", tracing_enabled=False)
    agent = SqlAgent(create_engine("sqlite://"), config=config)
    graph = build_agent_graph(agent, config, lambda *args, **kwargs: None)
    mermaid = graph.get_graph().draw_mermaid()
    OUT.write_text(HEADER + "```mermaid\n" + mermaid.rstrip() + "\n```\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
